// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type Material struct {
	MaterialID  interface{}
	Unit        string
	Description sql.NullString
}

type MaterialName struct {
	NameID     interface{}
	MaterialID int64
	Name       string
	IsPrimary  bool
}

type Product struct {
	ProductID   interface{}
	Name        string
	Description sql.NullString
	Price       interface{}
}

type ProductMaterial struct {
	ProductID  sql.NullInt64
	MaterialID sql.NullInt64
	Quantity   interface{}
}
