// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
)

const addMaterialName = `-- name: AddMaterialName :one
INSERT INTO
  material_names (material_id, name, is_primary)
VALUES
  (?, ?, ?) RETURNING name_id, material_id, name, is_primary
`

type AddMaterialNameParams struct {
	MaterialID int64
	Name       string
	IsPrimary  bool
}

func (q *Queries) AddMaterialName(ctx context.Context, arg AddMaterialNameParams) (MaterialName, error) {
	row := q.db.QueryRowContext(ctx, addMaterialName, arg.MaterialID, arg.Name, arg.IsPrimary)
	var i MaterialName
	err := row.Scan(
		&i.NameID,
		&i.MaterialID,
		&i.Name,
		&i.IsPrimary,
	)
	return i, err
}

const addProductMaterial = `-- name: AddProductMaterial :exec
insert into
  product_materials (product_id, material_id, quantity, quantity_text)
values
  (?, ?, ?, ?)
`

type AddProductMaterialParams struct {
	ProductID    sql.NullInt64
	MaterialID   sql.NullInt64
	Quantity     interface{}
	QuantityText sql.NullString
}

func (q *Queries) AddProductMaterial(ctx context.Context, arg AddProductMaterialParams) error {
	_, err := q.db.ExecContext(ctx, addProductMaterial,
		arg.ProductID,
		arg.MaterialID,
		arg.Quantity,
		arg.QuantityText,
	)
	return err
}

const deleteAllMaterialNames = `-- name: DeleteAllMaterialNames :exec
DELETE FROM material_names
WHERE
  material_id = ?
`

func (q *Queries) DeleteAllMaterialNames(ctx context.Context, materialID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllMaterialNames, materialID)
	return err
}

const deleteAllProductMaterials = `-- name: DeleteAllProductMaterials :exec
DELETE FROM product_materials
WHERE
  product_id = ?
`

func (q *Queries) DeleteAllProductMaterials(ctx context.Context, productID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteAllProductMaterials, productID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE
  file_id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, fileID)
	return err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM materials
WHERE
  material_id = ?
`

func (q *Queries) DeleteMaterial(ctx context.Context, materialID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMaterial, materialID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE
  product_id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, productID)
	return err
}

const deleteProductFile = `-- name: DeleteProductFile :exec
DELETE FROM files
WHERE
  file_id = ?
`

func (q *Queries) DeleteProductFile(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductFile, fileID)
	return err
}

const deleteProductMaterial = `-- name: DeleteProductMaterial :exec
delete from product_materials
where
  product_id = ?
  and material_id = ?
`

type DeleteProductMaterialParams struct {
	ProductID  sql.NullInt64
	MaterialID sql.NullInt64
}

func (q *Queries) DeleteProductMaterial(ctx context.Context, arg DeleteProductMaterialParams) error {
	_, err := q.db.ExecContext(ctx, deleteProductMaterial, arg.ProductID, arg.MaterialID)
	return err
}

const getAllMaterials = `-- name: GetAllMaterials :many
SELECT
  materials.material_id, materials.unit_id, materials.description,
  unit_types.unit AS unit,
  material_names.name AS name,
  product_materials.quantity AS quantity,
  product_materials.quantity_text AS quantity_text
FROM
  materials
  inner join unit_types on materials.unit_id = unit_types.unit_id
  inner join material_names on material_names.material_id = materials.material_id
  inner join product_materials on product_materials.material_id = materials.material_id
where
  is_primary = TRUE
`

type GetAllMaterialsRow struct {
	MaterialID   int64
	UnitID       int64
	Description  sql.NullString
	Unit         string
	Name         string
	Quantity     interface{}
	QuantityText sql.NullString
}

func (q *Queries) GetAllMaterials(ctx context.Context) ([]GetAllMaterialsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMaterialsRow
	for rows.Next() {
		var i GetAllMaterialsRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.UnitID,
			&i.Description,
			&i.Unit,
			&i.Name,
			&i.Quantity,
			&i.QuantityText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
  product_id, name, description
FROM
  products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.ProductID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUnits = `-- name: GetAllUnits :many
SELECT
  unit_id, unit
FROM
  unit_types
`

func (q *Queries) GetAllUnits(ctx context.Context) ([]UnitType, error) {
	rows, err := q.db.QueryContext(ctx, getAllUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitType
	for rows.Next() {
		var i UnitType
		if err := rows.Scan(&i.UnitID, &i.Unit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialByID = `-- name: GetMaterialByID :one
SELECT
  materials.material_id, materials.unit_id, materials.description,
  unit_types.unit AS unit,
  product_materials.quantity AS quantity
FROM
  materials
  inner join unit_types on materials.unit_id = unit_types.unit_id
  inner join product_materials on product_materials.material_id = materials.material_id
WHERE
  materials.material_id = ?
`

type GetMaterialByIDRow struct {
	MaterialID  int64
	UnitID      int64
	Description sql.NullString
	Unit        string
	Quantity    interface{}
}

func (q *Queries) GetMaterialByID(ctx context.Context, materialID int64) (GetMaterialByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterialByID, materialID)
	var i GetMaterialByIDRow
	err := row.Scan(
		&i.MaterialID,
		&i.UnitID,
		&i.Description,
		&i.Unit,
		&i.Quantity,
	)
	return i, err
}

const getMaterialByName = `-- name: GetMaterialByName :one
select
  m.material_id, m.unit_id, m.description,
  pm.quantity AS quantity,
  pm.quantity_text AS quantity_text,
  mn.name AS material_name,
  ut.unit AS unit
from
  materials m
  inner join product_materials pm on m.material_id = pm.material_id
  inner join material_names mn on m.material_id = mn.material_id
  inner join unit_types ut on ut.unit_id = m.unit_id
where
  name = ?
`

type GetMaterialByNameRow struct {
	MaterialID   int64
	UnitID       int64
	Description  sql.NullString
	Quantity     interface{}
	QuantityText sql.NullString
	MaterialName string
	Unit         string
}

func (q *Queries) GetMaterialByName(ctx context.Context, name string) (GetMaterialByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterialByName, name)
	var i GetMaterialByNameRow
	err := row.Scan(
		&i.MaterialID,
		&i.UnitID,
		&i.Description,
		&i.Quantity,
		&i.QuantityText,
		&i.MaterialName,
		&i.Unit,
	)
	return i, err
}

const getMaterialFiles = `-- name: GetMaterialFiles :many
SELECT
  f.file_id, f.name, f.path,
  fm.material_id AS material_id
FROM
  files f
  INNER JOIN files_materials fm ON f.file_id = fm.file_id
WHERE
  fm.material_id = ?
`

type GetMaterialFilesRow struct {
	FileID     int64
	Name       string
	Path       sql.NullString
	MaterialID sql.NullInt64
}

func (q *Queries) GetMaterialFiles(ctx context.Context, materialID sql.NullInt64) ([]GetMaterialFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialFiles, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialFilesRow
	for rows.Next() {
		var i GetMaterialFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.Name,
			&i.Path,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialNames = `-- name: GetMaterialNames :many
;

select
  name_id, material_id, name, is_primary
from
  material_names
where
  material_id = ?
`

func (q *Queries) GetMaterialNames(ctx context.Context, materialID int64) ([]MaterialName, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialNames, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialName
	for rows.Next() {
		var i MaterialName
		if err := rows.Scan(
			&i.NameID,
			&i.MaterialID,
			&i.Name,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialProducts = `-- name: GetMaterialProducts :many
SELECT
  p.product_id, p.name, p.description,
  pm.quantity AS quantity,
  pm.quantity_text AS quantity_text,
  ut.unit AS unit
FROM
  products p
  INNER JOIN product_materials pm ON p.product_id = pm.product_id
  INNER JOIN materials m ON m.material_id = pm.material_id
  INNER JOIN unit_types ut ON ut.unit_id = m.unit_id
WHERE
  pm.material_id = ?
`

type GetMaterialProductsRow struct {
	ProductID    int64
	Name         string
	Description  sql.NullString
	Quantity     interface{}
	QuantityText sql.NullString
	Unit         string
}

func (q *Queries) GetMaterialProducts(ctx context.Context, materialID sql.NullInt64) ([]GetMaterialProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialProducts, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialProductsRow
	for rows.Next() {
		var i GetMaterialProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.QuantityText,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  product_id, name, description
FROM
  products
WHERE
  product_id = ?
`

func (q *Queries) GetProductByID(ctx context.Context, productID int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, productID)
	var i Product
	err := row.Scan(&i.ProductID, &i.Name, &i.Description)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
select
  product_id, name, description
from
  products
where
  name = ?
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, name)
	var i Product
	err := row.Scan(&i.ProductID, &i.Name, &i.Description)
	return i, err
}

const getProductFiles = `-- name: GetProductFiles :many
SELECT
  f.file_id, f.name, f.path,
  fp.product_id AS product_id
FROM
  files f
  INNER JOIN files_products fp ON f.file_id = fp.file_id
WHERE
  fp.product_id = ?
`

type GetProductFilesRow struct {
	FileID    int64
	Name      string
	Path      sql.NullString
	ProductID sql.NullInt64
}

func (q *Queries) GetProductFiles(ctx context.Context, productID sql.NullInt64) ([]GetProductFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductFiles, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductFilesRow
	for rows.Next() {
		var i GetProductFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.Name,
			&i.Path,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductMaterials = `-- name: GetProductMaterials :many
SELECT
  m.material_id, m.unit_id, m.description,
  ut.unit AS unit,
  pm.quantity AS quantity,
  pm.quantity_text AS quantity_text,
  mn.name AS material_name
FROM
  product_materials pm
  INNER JOIN materials m ON m.material_id = pm.material_id
  INNER JOIN unit_types ut ON ut.unit_id = m.unit_id
  INNER JOIN material_names mn ON mn.material_id = m.material_id
WHERE
  pm.product_id = ?
  and mn.is_primary = TRUE
`

type GetProductMaterialsRow struct {
	MaterialID   int64
	UnitID       int64
	Description  sql.NullString
	Unit         string
	Quantity     interface{}
	QuantityText sql.NullString
	MaterialName string
}

func (q *Queries) GetProductMaterials(ctx context.Context, productID sql.NullInt64) ([]GetProductMaterialsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductMaterials, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductMaterialsRow
	for rows.Next() {
		var i GetProductMaterialsRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.UnitID,
			&i.Description,
			&i.Unit,
			&i.Quantity,
			&i.QuantityText,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT unit_id, unit from unit_types
where unit_id = ?
`

func (q *Queries) GetUnitByID(ctx context.Context, unitID int64) (UnitType, error) {
	row := q.db.QueryRowContext(ctx, getUnitByID, unitID)
	var i UnitType
	err := row.Scan(&i.UnitID, &i.Unit)
	return i, err
}

const getUnitByName = `-- name: GetUnitByName :one
select
  unit_id, unit
from
  unit_types
where
  unit = ?
`

func (q *Queries) GetUnitByName(ctx context.Context, unit string) (UnitType, error) {
	row := q.db.QueryRowContext(ctx, getUnitByName, unit)
	var i UnitType
	err := row.Scan(&i.UnitID, &i.Unit)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO
  files (name, path)
VALUES
  (?, ?) RETURNING file_id, name, path
`

type InsertFileParams struct {
	Name string
	Path sql.NullString
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile, arg.Name, arg.Path)
	var i File
	err := row.Scan(&i.FileID, &i.Name, &i.Path)
	return i, err
}

const insertMaterial = `-- name: InsertMaterial :one
INSERT INTO
  materials (unit_id, description)
VALUES
  (
    (
      SELECT
        unit_id
      FROM
        unit_types
      WHERE
        unit_types.unit = ?
    ),
    ?
  ) RETURNING material_id, unit_id, description
`

type InsertMaterialParams struct {
	Unit        string
	Description sql.NullString
}

func (q *Queries) InsertMaterial(ctx context.Context, arg InsertMaterialParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, insertMaterial, arg.Unit, arg.Description)
	var i Material
	err := row.Scan(&i.MaterialID, &i.UnitID, &i.Description)
	return i, err
}

const insertMaterialFile = `-- name: InsertMaterialFile :one
INSERT INTO
  files_materials (material_id, file_id)
VALUES
  (?, ?) RETURNING material_id, file_id
`

type InsertMaterialFileParams struct {
	MaterialID sql.NullInt64
	FileID     sql.NullInt64
}

func (q *Queries) InsertMaterialFile(ctx context.Context, arg InsertMaterialFileParams) (FilesMaterial, error) {
	row := q.db.QueryRowContext(ctx, insertMaterialFile, arg.MaterialID, arg.FileID)
	var i FilesMaterial
	err := row.Scan(&i.MaterialID, &i.FileID)
	return i, err
}

const insertMaterialName = `-- name: InsertMaterialName :one
INSERT INTO
  material_names (material_id, name, is_primary)
VALUES
  (?, ?, ?) RETURNING name_id, material_id, name, is_primary
`

type InsertMaterialNameParams struct {
	MaterialID int64
	Name       string
	IsPrimary  bool
}

func (q *Queries) InsertMaterialName(ctx context.Context, arg InsertMaterialNameParams) (MaterialName, error) {
	row := q.db.QueryRowContext(ctx, insertMaterialName, arg.MaterialID, arg.Name, arg.IsPrimary)
	var i MaterialName
	err := row.Scan(
		&i.NameID,
		&i.MaterialID,
		&i.Name,
		&i.IsPrimary,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO
  products (name, description)
VALUES
  (?, ?) RETURNING product_id, name, description
`

type InsertProductParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct, arg.Name, arg.Description)
	var i Product
	err := row.Scan(&i.ProductID, &i.Name, &i.Description)
	return i, err
}

const insertProductFile = `-- name: InsertProductFile :one
INSERT INTO
  files_products (product_id, file_id)
VALUES
  (?, ?) RETURNING product_id, file_id
`

type InsertProductFileParams struct {
	ProductID sql.NullInt64
	FileID    sql.NullInt64
}

func (q *Queries) InsertProductFile(ctx context.Context, arg InsertProductFileParams) (FilesProduct, error) {
	row := q.db.QueryRowContext(ctx, insertProductFile, arg.ProductID, arg.FileID)
	var i FilesProduct
	err := row.Scan(&i.ProductID, &i.FileID)
	return i, err
}

const setMaterialPrimaryName = `-- name: SetMaterialPrimaryName :exec
UPDATE material_names
SET
  is_primary = TRUE
WHERE
  name = ?
`

func (q *Queries) SetMaterialPrimaryName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, setMaterialPrimaryName, name)
	return err
}

const unsetMaterialPrimaryName = `-- name: UnsetMaterialPrimaryName :exec
UPDATE material_names
SET
  is_primary = FALSE
WHERE
  is_primary = TRUE
  AND material_id = ?
`

func (q *Queries) UnsetMaterialPrimaryName(ctx context.Context, materialID int64) error {
	_, err := q.db.ExecContext(ctx, unsetMaterialPrimaryName, materialID)
	return err
}

const updateMaterialDescription = `-- name: UpdateMaterialDescription :one
UPDATE materials
SET
  description = ?
WHERE
  material_id = ? RETURNING material_id, unit_id, description
`

type UpdateMaterialDescriptionParams struct {
	Description sql.NullString
	MaterialID  int64
}

func (q *Queries) UpdateMaterialDescription(ctx context.Context, arg UpdateMaterialDescriptionParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, updateMaterialDescription, arg.Description, arg.MaterialID)
	var i Material
	err := row.Scan(&i.MaterialID, &i.UnitID, &i.Description)
	return i, err
}

const updateMaterialPrimaryName = `-- name: UpdateMaterialPrimaryName :one
UPDATE material_names
SET
  name = ?
WHERE
  material_id = ? RETURNING name_id, material_id, name, is_primary
`

type UpdateMaterialPrimaryNameParams struct {
	Name       string
	MaterialID int64
}

func (q *Queries) UpdateMaterialPrimaryName(ctx context.Context, arg UpdateMaterialPrimaryNameParams) (MaterialName, error) {
	row := q.db.QueryRowContext(ctx, updateMaterialPrimaryName, arg.Name, arg.MaterialID)
	var i MaterialName
	err := row.Scan(
		&i.NameID,
		&i.MaterialID,
		&i.Name,
		&i.IsPrimary,
	)
	return i, err
}

const updateMaterialUnit = `-- name: UpdateMaterialUnit :one
UPDATE materials
SET
  unit = (
    SELECT
      unit_id
    FROM
      unit_types
    WHERE
      unit_types.unit = ?
  )
WHERE
  material_id = ? RETURNING material_id, unit_id, description
`

type UpdateMaterialUnitParams struct {
	Unit       string
	MaterialID int64
}

func (q *Queries) UpdateMaterialUnit(ctx context.Context, arg UpdateMaterialUnitParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, updateMaterialUnit, arg.Unit, arg.MaterialID)
	var i Material
	err := row.Scan(&i.MaterialID, &i.UnitID, &i.Description)
	return i, err
}

const updateProductDescription = `-- name: UpdateProductDescription :exec
UPDATE products
SET
  description = ?
WHERE
  product_id = ? RETURNING product_id, name, description
`

type UpdateProductDescriptionParams struct {
	Description sql.NullString
	ProductID   int64
}

func (q *Queries) UpdateProductDescription(ctx context.Context, arg UpdateProductDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateProductDescription, arg.Description, arg.ProductID)
	return err
}

const updateProductMaterial = `-- name: UpdateProductMaterial :exec
UPDATE product_materials
SET
  quantity = ?,
  quantity_text = ?
WHERE
  product_id = ?
  AND material_id = ?
`

type UpdateProductMaterialParams struct {
	Quantity     interface{}
	QuantityText sql.NullString
	ProductID    sql.NullInt64
	MaterialID   sql.NullInt64
}

func (q *Queries) UpdateProductMaterial(ctx context.Context, arg UpdateProductMaterialParams) error {
	_, err := q.db.ExecContext(ctx, updateProductMaterial,
		arg.Quantity,
		arg.QuantityText,
		arg.ProductID,
		arg.MaterialID,
	)
	return err
}

const updateProductName = `-- name: UpdateProductName :exec
UPDATE products
SET
  name = ?
WHERE
  product_id = ? RETURNING product_id, name, description
`

type UpdateProductNameParams struct {
	Name      string
	ProductID int64
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProductName, arg.Name, arg.ProductID)
	return err
}
