// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/s-588/BOMViewer/cmd/config"

func SettingsForm(config config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"/config\" hx-target=\"#settings-message\" hx-swap=\"outerHTML\"><div class=\"card shadow-sm mb-4\"><div class=\"card-header bg-primary text-white\"><h5 class=\"mb-0\"><i class=\"fas fa-folder me-2\"></i>Базовые настройки</h5></div><div class=\"card-body\"><div class=\"mb-3\"><label for=\"base_directory\" class=\"form-label\">Корневая директория</label><div class=\"input-group\"><span class=\"input-group-text\"><i class=\"fas fa-folder-open\"></i></span> <input type=\"text\" class=\"form-control\" id=\"base_directory\" name=\"base_directory\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(config.BaseDirectory)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/settings.templ`, Line: 21, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" required placeholder=\"e.g., data\"></div><div class=\"form-text\">Название папки где будут храниться данные приложения</div></div></div></div><div class=\"card shadow-sm mb-4\"><div class=\"card-header bg-secondary text-white\"><h5 class=\"mb-0\"><i class=\"fas fa-server me-2\"></i>Настройки сервера</h5></div><div class=\"card-body\"><div class=\"mb-3\"><label for=\"uploads_directory\" class=\"form-label\">Порт</label><div class=\"input-group\"><span class=\"input-group-text\"><i class=\"fas fa-upload\"></i></span> <input type=\"text\" class=\"form-control\" id=\"server_port\" name=\"server.server_port\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(config.ServerCfg.ServerPort)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/settings.templ`, Line: 44, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" required placeholder=\"8080\"></div><div class=\"form-text\">Порт который использует сервер. Если указано значение 0 - порт будет назначаться операционной системой</div></div></div><div class=\"card-body\"><div class=\"mb-3\"><label for=\"uploads_directory\" class=\"form-label\">Директория загрузок</label><div class=\"input-group\"><span class=\"input-group-text\"><i class=\"fas fa-upload\"></i></span> <input type=\"text\" class=\"form-control\" id=\"uploads_directory\" name=\"server.uploads_directory\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(config.ServerCfg.UploadsDir)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/settings.templ`, Line: 62, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" required placeholder=\"e.g., uploads\"></div><div class=\"form-text\">Название папки в которой будут хранится прикреплённые файлы, относительно корневой директории.</div></div></div></div><div class=\"card shadow-sm mb-4\"><div class=\"card-header bg-success text-white\"><h5 class=\"mb-0\"><i class=\"fas fa-database me-2\"></i>Настройки базы данных</h5></div><div class=\"card-body\"><div class=\"mb-3\"><label for=\"database_name\" class=\"form-label\">Название базы данных</label><div class=\"input-group\"><span class=\"input-group-text\"><i class=\"fas fa-database\"></i></span> <input type=\"text\" class=\"form-control\" id=\"database_name\" name=\"database.database_name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(config.DBCfg.DBName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/settings.templ`, Line: 85, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" required placeholder=\"e.g., database.db\"></div><div class=\"form-text\">Название файла базы данных, относительно корневой директории.</div></div></div></div><div class=\"card shadow-sm mb-4\"><div class=\"card-header bg-warning text-dark\"><h5 class=\"mb-0\"><i class=\"fas fa-clipboard-list me-2\"></i>Настройки логирования</h5></div><div class=\"card-body\"><div class=\"mb-3\"><label for=\"log_level\" class=\"form-label\">Уровень логирования</label> <select class=\"form-select\" id=\"log_level\" name=\"log.log_level\" required>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = logLevelOptions(config.LogCfg.LogLevel).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</select><div class=\"form-text\">Минимальная значимость для записи лога.</div></div></div></div><div class=\"d-flex justify-content-between align-items-center\"><button type=\"button\" class=\"btn btn-outline-secondary\" hx-delete=\"/config\" hx-target=\"#settings-form\" hx-swap=\"outerHTML\" hx-confirm=\"Reset all settings to defaults?\"><i class=\"fas fa-undo me-1\"></i> Сбросить</button><div class=\"d-flex gap-2\"><button type=\"submit\" class=\"btn btn-primary\" hx-indicator=\"#settings-spinner\"><span id=\"settings-spinner\" class=\"spinner-border spinner-border-sm htmx-indicator me-1\" role=\"status\"></span> <i class=\"fas fa-save me-1\"></i> Сохранить</button></div></div><div id=\"settings-message\" class=\"mt-3\"></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func logLevelOptions(currentLevel string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<option value=\"DEBUG\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if "DEBUG" == currentLevel {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">DEBUG - Все сообщения</option> <option value=\"INFO\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if "INFO" == currentLevel {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, ">INFO - Информационные, предупреждения и ошибки</option> <option value=\"WARN\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if "WARN" == currentLevel {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, ">WARN - Предупреждения и ошибки</option> <option value=\"ERROR\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if "ERROR" == currentLevel {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, ">ERROR - Только ошибки</option>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
