// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlite

import (
	"context"
	"database/sql"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE
    file_id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, fileID)
	return err
}

const deleteProductFile = `-- name: DeleteProductFile :exec
DELETE FROM files
WHERE
    file_id = ?
`

func (q *Queries) DeleteProductFile(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductFile, fileID)
	return err
}

const getMaterialFiles = `-- name: GetMaterialFiles :many
SELECT
    f.file_id, f.name, f.path,
    fm.material_id AS material_id
FROM
    files f
    INNER JOIN files_materials fm ON f.file_id = fm.file_id
WHERE
    fm.material_id = ?
`

type GetMaterialFilesRow struct {
	FileID     int64
	Name       string
	Path       sql.NullString
	MaterialID sql.NullInt64
}

func (q *Queries) GetMaterialFiles(ctx context.Context, materialID sql.NullInt64) ([]GetMaterialFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialFiles, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialFilesRow
	for rows.Next() {
		var i GetMaterialFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.Name,
			&i.Path,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductFiles = `-- name: GetProductFiles :many
SELECT
    f.file_id, f.name, f.path,
    fp.product_id AS product_id
FROM
    files f
    INNER JOIN files_products fp ON f.file_id = fp.file_id
WHERE
    fp.product_id = ?
`

type GetProductFilesRow struct {
	FileID    int64
	Name      string
	Path      sql.NullString
	ProductID sql.NullInt64
}

func (q *Queries) GetProductFiles(ctx context.Context, productID sql.NullInt64) ([]GetProductFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductFiles, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductFilesRow
	for rows.Next() {
		var i GetProductFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.Name,
			&i.Path,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :one
INSERT INTO
    files (name, path)
VALUES
    (?, ?) RETURNING file_id, name, path
`

type InsertFileParams struct {
	Name string
	Path sql.NullString
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile, arg.Name, arg.Path)
	var i File
	err := row.Scan(&i.FileID, &i.Name, &i.Path)
	return i, err
}

const insertMaterialFile = `-- name: InsertMaterialFile :one
INSERT INTO
    files_materials (material_id, file_id)
VALUES
    (?, ?) RETURNING material_id, file_id
`

type InsertMaterialFileParams struct {
	MaterialID sql.NullInt64
	FileID     sql.NullInt64
}

func (q *Queries) InsertMaterialFile(ctx context.Context, arg InsertMaterialFileParams) (FilesMaterial, error) {
	row := q.db.QueryRowContext(ctx, insertMaterialFile, arg.MaterialID, arg.FileID)
	var i FilesMaterial
	err := row.Scan(&i.MaterialID, &i.FileID)
	return i, err
}

const insertProductFile = `-- name: InsertProductFile :one
INSERT INTO
    files_products (product_id, file_id)
VALUES
    (?, ?) RETURNING product_id, file_id
`

type InsertProductFileParams struct {
	ProductID sql.NullInt64
	FileID    sql.NullInt64
}

func (q *Queries) InsertProductFile(ctx context.Context, arg InsertProductFileParams) (FilesProduct, error) {
	row := q.db.QueryRowContext(ctx, insertProductFile, arg.ProductID, arg.FileID)
	var i FilesProduct
	err := row.Scan(&i.ProductID, &i.FileID)
	return i, err
}
