// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type File struct {
	FileID int64
	Name   string
	Path   sql.NullString
}

type FilesMaterial struct {
	MaterialID sql.NullInt64
	FileID     sql.NullInt64
}

type FilesProduct struct {
	ProductID sql.NullInt64
	FileID    sql.NullInt64
}

type FtsAll struct {
	Type  string
	RefID string
	Text  string
}

type Material struct {
	MaterialID  int64
	UnitID      int64
	Description sql.NullString
}

type MaterialName struct {
	NameID     int64
	MaterialID int64
	Name       string
	IsPrimary  bool
}

type Product struct {
	ProductID   int64
	Name        string
	Description sql.NullString
}

type ProductMaterial struct {
	ProductID    sql.NullInt64
	MaterialID   sql.NullInt64
	Quantity     interface{}
	QuantityText sql.NullString
}

type UnitType struct {
	UnitID int64
	Unit   string
}
