// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlite

import (
	"context"
	"database/sql"
)

const addProductMaterial = `-- name: AddProductMaterial :exec
insert into
    product_materials (product_id, material_id, quantity, quantity_text)
values
    (?, ?, ?, ?)
`

type AddProductMaterialParams struct {
	ProductID    sql.NullInt64
	MaterialID   sql.NullInt64
	Quantity     interface{}
	QuantityText sql.NullString
}

func (q *Queries) AddProductMaterial(ctx context.Context, arg AddProductMaterialParams) error {
	_, err := q.db.ExecContext(ctx, addProductMaterial,
		arg.ProductID,
		arg.MaterialID,
		arg.Quantity,
		arg.QuantityText,
	)
	return err
}

const deleteAllProductMaterials = `-- name: DeleteAllProductMaterials :exec
DELETE FROM product_materials
WHERE
    product_id = ?
`

func (q *Queries) DeleteAllProductMaterials(ctx context.Context, productID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteAllProductMaterials, productID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE
    product_id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, productID)
	return err
}

const deleteProductMaterial = `-- name: DeleteProductMaterial :exec
delete from product_materials
where
    product_id = ?
    and material_id = ?
`

type DeleteProductMaterialParams struct {
	ProductID  sql.NullInt64
	MaterialID sql.NullInt64
}

func (q *Queries) DeleteProductMaterial(ctx context.Context, arg DeleteProductMaterialParams) error {
	_, err := q.db.ExecContext(ctx, deleteProductMaterial, arg.ProductID, arg.MaterialID)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    p.product_id,
    p.name,
    p.description,
    pm.material_id,
    mn.name as material_name,
    m.unit_id,
    ut.unit as unit_name,
    pm.quantity,
    pm.quantity_text
FROM
    products p
    LEFT JOIN product_materials pm ON p.product_id = pm.product_id
    LEFT JOIN materials m ON pm.material_id = m.material_id
    LEFT JOIN material_names mn ON m.material_id = mn.material_id
    AND mn.is_primary = TRUE
    LEFT JOIN unit_types ut ON m.unit_id = ut.unit_id
ORDER BY
    p.product_id
`

type GetAllProductsRow struct {
	ProductID    int64
	Name         string
	Description  sql.NullString
	MaterialID   sql.NullInt64
	MaterialName sql.NullString
	UnitID       sql.NullInt64
	UnitName     sql.NullString
	Quantity     interface{}
	QuantityText sql.NullString
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
			&i.MaterialName,
			&i.UnitID,
			&i.UnitName,
			&i.Quantity,
			&i.QuantityText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    product_id, name, description
FROM
    products
WHERE
    product_id = ?
`

func (q *Queries) GetProductByID(ctx context.Context, productID int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, productID)
	var i Product
	err := row.Scan(&i.ProductID, &i.Name, &i.Description)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
select
    product_id, name, description
from
    products
where
    name = ?
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, name)
	var i Product
	err := row.Scan(&i.ProductID, &i.Name, &i.Description)
	return i, err
}

const getProductMaterials = `-- name: GetProductMaterials :many
SELECT
    m.material_id, m.unit_id, m.description,
    ut.unit AS unit,
    pm.quantity AS quantity,
    pm.quantity_text AS quantity_text,
    mn.name AS material_name
FROM
    product_materials pm
    INNER JOIN materials m ON m.material_id = pm.material_id
    INNER JOIN unit_types ut ON ut.unit_id = m.unit_id
    INNER JOIN material_names mn ON mn.material_id = m.material_id
WHERE
    pm.product_id = ?
    and mn.is_primary = TRUE
`

type GetProductMaterialsRow struct {
	MaterialID   int64
	UnitID       int64
	Description  sql.NullString
	Unit         string
	Quantity     interface{}
	QuantityText sql.NullString
	MaterialName string
}

func (q *Queries) GetProductMaterials(ctx context.Context, productID sql.NullInt64) ([]GetProductMaterialsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductMaterials, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductMaterialsRow
	for rows.Next() {
		var i GetProductMaterialsRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.UnitID,
			&i.Description,
			&i.Unit,
			&i.Quantity,
			&i.QuantityText,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO
    products (name, description)
VALUES
    (?, ?) RETURNING product_id, name, description
`

type InsertProductParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct, arg.Name, arg.Description)
	var i Product
	err := row.Scan(&i.ProductID, &i.Name, &i.Description)
	return i, err
}

const updateProductDescription = `-- name: UpdateProductDescription :exec
UPDATE products
SET
    description = ?
WHERE
    product_id = ? RETURNING product_id, name, description
`

type UpdateProductDescriptionParams struct {
	Description sql.NullString
	ProductID   int64
}

func (q *Queries) UpdateProductDescription(ctx context.Context, arg UpdateProductDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateProductDescription, arg.Description, arg.ProductID)
	return err
}

const updateProductMaterial = `-- name: UpdateProductMaterial :exec
UPDATE product_materials
SET
    quantity = ?,
    quantity_text = ?
WHERE
    product_id = ?
    AND material_id = ?
`

type UpdateProductMaterialParams struct {
	Quantity     interface{}
	QuantityText sql.NullString
	ProductID    sql.NullInt64
	MaterialID   sql.NullInt64
}

func (q *Queries) UpdateProductMaterial(ctx context.Context, arg UpdateProductMaterialParams) error {
	_, err := q.db.ExecContext(ctx, updateProductMaterial,
		arg.Quantity,
		arg.QuantityText,
		arg.ProductID,
		arg.MaterialID,
	)
	return err
}

const updateProductName = `-- name: UpdateProductName :exec
UPDATE products
SET
    name = ?
WHERE
    product_id = ? RETURNING product_id, name, description
`

type UpdateProductNameParams struct {
	Name      string
	ProductID int64
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProductName, arg.Name, arg.ProductID)
	return err
}
