// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sqlite

import (
	"context"
)

const search = `-- name: Search :many
SELECT
    type, ref_id, text
FROM
    fts_all
WHERE
    text MATCH ?
ORDER BY
    score
LIMIT
    ?
`

type SearchParams struct {
	Text  string
	Limit int64
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]FtsAll, error) {
	rows, err := q.db.QueryContext(ctx, search, arg.Text, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FtsAll
	for rows.Next() {
		var i FtsAll
		if err := rows.Scan(&i.Type, &i.RefID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
