// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sqlite

import (
	"context"
)

const searchAll = `-- name: SearchAll :many
SELECT
    fa.type,
    fa.ref_id,
    fa.text,
    COALESCE(
        case
            when fa.type = 'product' then p.name
            ELSE mn.name
        end,
        ''
    ) AS name
FROM
    fts_all fa
    left join products p on fa.ref_id = p.id
    and fa.type = 'product'
    left join material_names mn on fa.ref_id = mn.id
    and fa.type = 'material'
    and mn.is_primary = true
WHERE
    text MATCH ?
LIMIT
    ?
`

type SearchAllParams struct {
	Text  string
	Limit int64
}

type SearchAllRow struct {
	Type  string
	RefID string
	Text  string
	Name  interface{}
}

func (q *Queries) SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAll, arg.Text, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllRow
	for rows.Next() {
		var i SearchAllRow
		if err := rows.Scan(
			&i.Type,
			&i.RefID,
			&i.Text,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
