// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package sqlite

import (
	"context"
)

const getAllUnits = `-- name: GetAllUnits :many
SELECT
    unit_id, unit
FROM
    unit_types
`

func (q *Queries) GetAllUnits(ctx context.Context) ([]UnitType, error) {
	rows, err := q.db.QueryContext(ctx, getAllUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitType
	for rows.Next() {
		var i UnitType
		if err := rows.Scan(&i.UnitID, &i.Unit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT
    unit_id, unit
from
    unit_types
where
    unit_id = ?
`

func (q *Queries) GetUnitByID(ctx context.Context, unitID int64) (UnitType, error) {
	row := q.db.QueryRowContext(ctx, getUnitByID, unitID)
	var i UnitType
	err := row.Scan(&i.UnitID, &i.Unit)
	return i, err
}

const getUnitByName = `-- name: GetUnitByName :one
select
    unit_id, unit
from
    unit_types
where
    unit = ?
`

func (q *Queries) GetUnitByName(ctx context.Context, unit string) (UnitType, error) {
	row := q.db.QueryRowContext(ctx, getUnitByName, unit)
	var i UnitType
	err := row.Scan(&i.UnitID, &i.Unit)
	return i, err
}
